.TH CAIRO-MSG 1 "29 July 14"
.SH NAME
cairo-msg \- display a message window
.SH SYNOPSIS
\fBcairo-msg\fP [ -u | -t | -p | -f | -T ] [ -s \fImessage\fP ]
.SH DESCRIPTION
\fBcairo-msg\fP displays a short notification
message in an \fIXwindow\fP on your screen at 
the specified position [\fB-p\fP], with the specified
level of \fIurgency\fP [\fB-u\fP], a \fItimeout\fP of
[\fB-t seconds\fP]and \fIfont\fP [\fB-f font\fP]if specified.
A [\fB-T "title"\fP] is also allowed.
Only the [\fB-s\fP] option is mandatory as it has the message.
.SS Options
.TP
\fB-u l|n|u\fP
\fIUrgency\fP. This requires an argument of
[\fBl\fP] for low urgency (grey), [\fBn\fP] for normal
urgency (blue) or [\fBu\fP] for high urgency (red).
The window background changes colour and icon changes.
.TP
\fB-t seconds\fP
\fITimeout\fP. The time in seconds to display the
message. The default is 10 seconds. 0 is forever.
.TP
\fB-p tl|tc|tr|cx|bl|bc|br\fR
\fIPosition\fP. Specify position on screen.
\fBtl\fP is \fItop left\fP,
\fBtc\fP is \fItop centre\fP,
\fBtr\fP is \fItop right\fP,
\fBcx\fP is \fIcentre of screen\fP,
\fBbl\fP is \fIbottom left\fP,
\fBbc\fP is \fIbottom centre\fP,
\fBbr\fP is \fIbottom right\fP, (default if not specified)
.TP
\fB-f "some font on your system"\fP
\fIFont\fP. A font to display the message. The default is Dejavu Sans
.TP
\fB-r style(int)\fP
\fIStyle\fP. [\fB0\fP] for nice rounded corners and no border; [\fB1\fP] for square corners
and a 1px border. [\fB1\fP] is the default.
.TP
\fB-T "a title"\fP
\fITitle\fP. A bold title limited to 20 characters
in the message which restricts the message body 
to the bottom line, a 36 character limit.
.TP
\fB-s "some message to display"\fP
\fIMessage\fP. A message string to display which must be quoted
with single or double quotes. Singe quotes are necessary when
some special characters are used. The message must be less than 70 
characters or the program will exit with an error.
.SH FILES
.TP
\fC/usr/bin/cairo-msg\fR
.SH "SEE ALSO"
yaf-splash(5), xmessage(5)
.SH BUGS
May not support wide chars well (CJK).
.SH "AUTHOR"
.IX Header "AUTHOR"
Michael Amadio - 01micko@gmail.com
.SH "COPYRIGHT AND LICENSE"
.IX Header "COPYRIGHT AND LICENSE"
\&\fBCopyright (C)\fR 2014 by Author.  
.PP
\&\fBcairo-msg\fR is free software; you can redistribute it and/or modify it
under the terms of the \s-1GPL-v2.0\s0.
